package com.prmgpregistrationsmi.model.Event;

public enum EventType {
    REGISTRATION_STARTED,
    EHR_REQUESTED,
    EHR_GENERATED,
    EHR_SENT,
    MIGRATE_STRUCTURED_RECORD_REQUEST,
    MIGRATE_STRUCTURED_RECORD_RESPONSE,
    MIGRATE_DOCUMENT_REQUEST,
    MIGRATE_DOCUMENT_RESPONSE,
    EHR_READY_TO_INTEGRATE,
    EHR_INTEGRATED,
    REGISTRATION_COMPLETED
}
