package com.prmgpregistrationsmi.model.Event;

public enum EventType {
    REGISTRATIONS,
    TRANSFER_COMPATIBILITY_STATUSES,
    EHR_REQUESTS,
    EHR_RESPONSES,
    DOCUMENT_RESPONSES,
    READY_TO_INTEGRATE_STATUSES,
    EHR_INTEGRATIONS,
    ERROR,
}
