#!/bin/bash

set -Eeo pipefail

for command in "$@"
do
  echo "--- ${command} ---"
  case "${command}" in
    _build)
        rm -rf build/
        gradle assemble
        ;;
    build)
        dojo "./tasks _build"
        ;;
    _test_unit)
        gradle test
        ;;
    test_unit)
        dojo "./tasks _test"
        ;;
    _test_integration)
        gradle --info integrationTest
        ;;
    test_integration)
        dojo "./tasks _test_integration"
        ;;
    _dep)
        gradle dependencyCheckAnalyze
        ;;
    dep)
        dojo "./tasks _dep"
        ;;
    _test_coverage)
        gradle jacocoTestCoverageVerification
        ;;
    test_coverage)
        dojo "./tasks _test_coverage"
        ;;
    _code_quality)
        gradle check -x test
        ;;
    code_quality)
        dojo "./tasks _code_quality"
        ;;
    run_local)
        ./gradlew bootRun
        ;;
    *)
        echo "Invalid command: '${command}'"
        exit 1
        ;;
  esac
done

set +e