package com.prmgpregistrationsmi.model.deprecated.Event;

public enum EventType {
    REGISTRATION_STARTED,
    PDS_TRACE,
    SDS_LOOKUP,
    PDS_UPDATE,
    EHR_REQUEST,
    EHR_RESPONSE,
    EHR_TRANSFER_COMPLETE,
    MIGRATE_STRUCTURED_RECORD_REQUEST,
    EHR_READY_TO_INTEGRATE,
    EHR_INTEGRATED,
    ERROR,
    INTERNAL_TRANSFER,
}
