mi_events_sns_topic_arn: ${MI_EVENTS_SNS_TOPIC_ARN:test_topic}

springdoc:
  show-actuator: true

  swagger-ui:
    path: /swagger

management:
  endpoints:
    web:
      base-path:
      path-mapping:
        health: /_status

cloud:
  aws:
    stack:
      auto: false

jolokia:
  username: ${MI_BASIC_AUTH_USERNAME:test_username}
  password: ${MI_BASIC_AUTH_PASSWORD:test_password}
