output_bucket: ${OUTPUT_MI_EVENTS_BUCKET:test_bucket}
splunk_cloud_url: ${SPLUNK_CLOUD_URL:splunk_cloud_url}
splunk_cloud_api_token: ${SPLUNK_CLOUD_API_TOKEN:test_token}

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger

cloud:
  aws:
    stack:
      auto: false