output_bucket: ${OUTPUT_MI_EVENTS_BUCKET:test_bucket}
splunk_cloud_url: ${SPLUNK_CLOUD_URL:splunk-cloud-url}

springdoc:
  show-actuator: true
  swagger-ui:
    path: /swagger

cloud:
  aws:
    stack:
      auto: false